on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build and deploy Nikola
        uses: getnikola/nikola-action@v8
        with:
          dry_run: false
